#!/usr/bin/env php
<?php

require __DIR__ . "/functions.php";

$time = microtime(true);

if($argc !== 2 || !is_dir($argv[1])) {
	exit("\033[1;36mUsage: \033[0;36m./dedupe <directory> \n\033[0m");
}

$count = 0;
$hashlist = [];
$path = realpath($argv[1]);
$files = array_diff(scandir($path), ["..", ".", ".DS_Store"]);

foreach($files as $f) {
	$progress();
	$hash = sha1_file("{$path}/{$f}");

	if(in_array($hash, $hashlist)) {
		rename("{$path}/{$f}", "{$path}/0_duplicate__{$f}");
		++$count;
	}
	
	$hashlist[] = $hash;
}

echo "\r";
echo "\033[1;36mFiles Checked: \033[0;36m" . count($files) . " \n";
echo "\033[1;36mDuplicate Files: \033[0;36m" . $count . " \n";
echo "\033[1;36mMemory Used: \033[0;36m" . round(memory_get_peak_usage()/1048576, 3) . " MB\n";
echo "\033[1;36mCompleted In: \033[0;36m" . round((microtime(true) - $time)*1000) . "ms \n\033[0m";

