#!/usr/bin/env php
<?php

$time = microtime(true);

if($argc !== 2 || !is_dir($argv[1])) {
	exit("\033[1;36mUsage: \033[0;36m./dedupe <directory> \n\033[0m");
}

$count = 0;
$hashlist = [];
$path = realpath($argv[1]);
$files = array_diff(scandir($path), ["..", "."]);

$prog = function() use (&$_prog_pos_, &$_prog_wait_)
{
	if($_prog_pos_ === null) {
		$_prog_pos_ = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']; // https://github.com/briandowns/spinner#available-character-sets
		$_prog_wait_ = microtime(1);
	}

	if($_prog_wait_ < microtime(1)) {
		$_prog_wait_ += 0.1;
		array_push($_prog_pos_, array_shift($_prog_pos_)); // making function calls for the hell of it
		echo "\r\033[1;36m" . $_prog_pos_[0];
	}
};

foreach($files as $f) {
	$prog();
	$hash = sha1_file("{$path}/{$f}");

	if(in_array($hash, $hashlist)) {
		rename("{$path}/{$f}", "{$path}/duplicate__{$f}");
		++$count;
	}
	
	array_push($hashlist, $hash);
}

echo "\r\033[1;36mFiles Checked: \033[0;36m" . count($files) . " \n";
echo "\033[1;36mDuplicate Files: \033[0;36m" . $count . " \n";
echo "\033[1;36mMemory Used: \033[0;36m" . round(memory_get_peak_usage()/1048576, 3) . " MB\n";
echo "\033[1;36mCompleted In: \033[0;36m" . round((microtime(true) - $time)*1000) . "ms \n\033[0m";

